# Generated by Django 4.0 on 2022-11-08 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0002_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('applied', models.BooleanField(default=False)),
                ('Denied', models.BooleanField(default=False)),
                ('Approved', models.BooleanField(default=False)),
                ('alloted', models.BooleanField(default=False)),
                ('alloted_slot', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
