# Generated by Django 4.0 on 2022-11-09 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='image',
        ),
    ]
