# Generated by Django 4.0 on 2022-11-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_application_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='img',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('DECLINED', 'DECLINED'), ('APPROVED', 'APPROVED')], default='PENDING', max_length=100, null=True),
        ),
    ]
