# Generated by Django 4.0 on 2022-11-10 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_application_pending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='Approved',
        ),
        migrations.RemoveField(
            model_name='application',
            name='Denied',
        ),
        migrations.RemoveField(
            model_name='application',
            name='alloted_slot',
        ),
        migrations.RemoveField(
            model_name='application',
            name='applied',
        ),
    ]
