# Generated by Django 4.0 on 2022-11-10 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_application_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='pending',
        ),
    ]
