# Generated by Django 4.0 on 2022-11-10 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_remove_application_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField(default=True)),
                ('reservedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.application')),
            ],
        ),
    ]
